AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for GitHub Actions

Parameters:
  RepositoryName:
    Type: String
    Description: Name of the GitHub repository
  GitHubUsername:
    Type: String
    Description: GitHub username

Resources:
  GitHubActionsRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: !Sub '${GitHubUsername}-${RepositoryName}-GitHubActionsRole'
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Principal: 
              Federated: 'arn:aws:iam::YOUR_ACCOUNT_ID:oidc-provider/token.actions.githubusercontent.com'
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition: 
              StringEquals: 
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubUsername}/${RepositoryName}:ref:refs/heads/main'
      Policies: 
        - PolicyName: 'GitHubActionsPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'ec2:DescribeInstances'
                  - 'ecs:CreateCluster'
                  - 'ecs:DeregisterContainerInstance'
                  - 'ecs:DiscoverPollEndpoint'
                  - 'ecs:Poll'
                  - 'ecs:RegisterContainerInstance'
                  - 'ecs:StartTelemetrySession'
                  - 'ecs:SubmitTaskStateChange'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 
                  - '*'

Outputs:
  GitHubActionsRoleArn:
    Description: "ARN of the GitHub Actions Role"
    Value: !GetAtt GitHubActionsRole.Arn