name: ECS Fargate Trend Inject

on:
  workflow_dispatch:
    inputs:
      filter_keywords:
        description: "Comma-separated list of keywords to filter task definitions"
        required: true
        default: "keyword1,keyword2,keyword3"

env:
  AWS_DEFAULT_REGION: us-east-1

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  fetch_task_definitions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_GH_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Fetch task definitions
        run: |
          aws ecs list-task-definitions > all_task_definitions.json
          echo ${{ github.event.inputs.filter_keywords }} | tr ',' '\n' > keywords.txt

      - name: Filter task definitions using jq
        run: |
          keywords=$(cat keywords.txt)
          jq -r --arg keywords "$keywords" '
            .taskDefinitionArns[] |
            select(contains($keywords))' all_task_definitions.json > filtered_task_definitions.txt

      - name: Print filtered task definitions
        run: |
          echo "Filtered Task Definitions:"
          cat filtered_task_definitions.txt

  update-ecs-task-definitions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          echo "Installing AWS CLI..."
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version
          if [ $? -ne 0 ]; then
            echo "Error: AWS CLI installation failed"
            exit 1
          fi
          echo "AWS CLI installed successfully"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_GH_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_DEFAULT_REGION }}