name: Update ECS Task Definitions

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  update-ecs-task-definitions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          echo "Installing AWS CLI..."
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version
          if [ $? -ne 0 ]; then
            echo "Error: AWS CLI installation failed"
            exit 1
          fi
          echo "AWS CLI installed successfully"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_GH_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Check for required files
        run: |
          if [ ! -f ./desired_task_definitions.txt ]; then
            echo "Error: desired_task_definitions.txt not found"
            exit 1
          fi

      - name: Display contents of desired_task_definitions.txt
        run: cat ./desired_task_definitions.txt

      - name: Retrieve current task definitions from AWS
        run: |
          aws ecs list-task-definitions > task_definitions_list.json
          if [ $? -ne 0 ]; then
            echo "Error: Failed to retrieve task definitions from AWS"
            exit 1
          fi

      - name: Process task definitions
        run: |
          > task_definitions_to_process.txt
          while IFS= read -r TASK_DEF; do
            echo "Processing task definition: $TASK_DEF"
            if grep -q "$TASK_DEF" ./task_definitions_list.json; then
              echo "$TASK_DEF exists, pulling and patching..."
              echo $TASK_DEF >> task_definitions_to_process.txt
            else
              echo "$TASK_DEF does not exist, skipping..."
            fi
          done < ./desired_task_definitions.txt

      - name: Describe task definitions
        run: |
          while IFS= read -r TASK_DEF; do
            aws ecs describe-task-definition --task-definition $TASK_DEF > current_task_definition.json
            if [ $? -ne 0 ]; then
              echo "Error: Failed to describe task definition $TASK_DEF"
              exit 1
            fi
            echo "Current task definition:"
            cat current_task_definition.json
          done < task_definitions_to_process.txt

      - name: Patch task definitions
        run: |
          while IFS= read -r TASK_DEF; do
            docker run -v $(pwd)/current_task_definition.json:/mnt/input/current_task_definition.json \
                       -v $(pwd)/patched_task_definition.json:/mnt/output/patched_task_definition.json \
                       trendmicrocloudone/ecs-taskdef-patcher:2.3.44 \
                       -i /mnt/input/current_task_definition.json \
                       -o /mnt/output/patched_task_definition.json
            if [ $? -ne 0 ]; then
              echo "Error: Failed to patch task definition $TASK_DEF"
              exit 1
            fi
            echo "Patched task definition:"
            cat $(pwd)/patched_task_definition.json
            cp $(pwd)/patched_task_definition.json path/to/terraform/configuration/$TASK_DEF.json
            if [ $? -ne 0 ]; then
              echo "Error: Failed to copy patched task definition $TASK_DEF"
              exit 1
            fi
          done < task_definitions_to_process.txt

      - name: Register new task definitions
        run: |
          while IFS= read -r TASK_DEF; do
            NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://$(pwd)/path/to/terraform/configuration/$TASK_DEF.json | jq -r '.taskDefinition.taskDefinitionArn')
            if [ $? -ne 0 ]; then
              echo "Error: Failed to register new task definition $TASK_DEF"
              exit 1
            fi
            echo "New task definition ARN: $NEW_TASK_DEF_ARN"
          done < task_definitions_to_process.txt